#!/bin/bash
# ==============================================================================
# Script: update.sh
# Description: 快速更新 AI CLI 配置，无需重新安装
#              修改 .env 后运行此脚本即可生效
# ==============================================================================

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}${BOLD}>>> AI CLI Config Update Tool${NC}"
echo "----------------------------------------------------------------"

# ==========================================
# [Phase 0] Initialization
# ==========================================
PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CONFIG_CONTAINER_DIR="$PROJECT_ROOT/.ai_tools_config"

# Load .env
if [ -f "$PROJECT_ROOT/.env" ]; then
    echo -e "${GREEN}📄 Loading configuration from .env...${NC}"
    set -a
    source "$PROJECT_ROOT/.env"
    set +a
else
    echo -e "${RED}❌ No .env file found!${NC}"
    exit 1
fi

# ==========================================
# [Phase 1] Configuration & Defaults
# ==========================================
CLAUDE_MODE=${CLAUDE_MODE:-isolated}
GEMINI_MODE=${GEMINI_MODE:-isolated}
CODEX_MODE=${CODEX_MODE:-global}

if [ "$CODEX_MODE" = "isolated" ]; then
    echo -e "${YELLOW}⚠️  Codex does not support isolated mode, using global${NC}"
    CODEX_MODE="global"
fi

CONDA_ENV_NAME=${CONDA_ENV_NAME:-ai_cli_env}
CLAUDE_URL=${CLAUDE_URL:-"https://api.anthropic.com"}
CLAUDE_MODEL=${CLAUDE_MODEL:-"claude-opus-4-5-20251101-thinking"}
CLAUDE_SMALL_MODEL=${CLAUDE_SMALL_MODEL:-"claude-haiku-4-5-20251001"}
GEMINI_URL=${GEMINI_URL:-"https://generativelanguage.googleapis.com"}
GEMINI_MODEL=${GEMINI_MODEL:-"gemini-2.5-pro"}
CODEX_URL=${CODEX_URL:-"https://api.openai.com/v1"}
CODEX_MODEL=${CODEX_MODEL:-"gpt-5.1-codex-max"}
CODEX_REASONING_EFFORT=${CODEX_REASONING_EFFORT:-"medium"}
CODEX_WIRE_API=${CODEX_WIRE_API:-"responses"}
CODEX_NETWORK_ACCESS=${CODEX_NETWORK_ACCESS:-"enabled"}
CODEX_DISABLE_RESPONSE_STORAGE=${CODEX_DISABLE_RESPONSE_STORAGE:-"true"}

# Check which CLI tools are installed
CLAUDE_INSTALLED=false
GEMINI_INSTALLED=false
CODEX_INSTALLED=false
command -v claude &> /dev/null && CLAUDE_INSTALLED=true
command -v gemini &> /dev/null && GEMINI_INSTALLED=true
command -v codex &> /dev/null && CODEX_INSTALLED=true

echo -e "\n${BLUE}>>> Updating configurations...${NC}"

# ==========================================
# [Phase 2] Update Claude Config
# ==========================================
if [ "$CLAUDE_MODE" = "isolated" ]; then
    echo -e "🔧 Claude: ${GREEN}isolated${NC} mode"
    CLAUDE_SECRETS="$CONFIG_CONTAINER_DIR/.private_config/claude.env"
    mkdir -p "$(dirname "$CLAUDE_SECRETS")"
    cat << EOF > "$CLAUDE_SECRETS"
export ANTHROPIC_BASE_URL="$CLAUDE_URL"
export ANTHROPIC_API_KEY="$CLAUDE_KEY"
export ANTHROPIC_AUTH_TOKEN="$CLAUDE_KEY"
export ANTHROPIC_MODEL="$CLAUDE_MODEL"
export ANTHROPIC_SMALL_FAST_MODEL="$CLAUDE_SMALL_MODEL"
EOF
    chmod 600 "$CLAUDE_SECRETS"
    echo -e "${GREEN}   ✅ Updated: $CLAUDE_SECRETS${NC}"

elif [ "$CLAUDE_MODE" = "global" ]; then
    echo -e "🔧 Claude: ${GREEN}global${NC} mode"
    CLAUDE_GLOBAL_CONFIG="$HOME/.claude_env"
    cat << EOF > "$CLAUDE_GLOBAL_CONFIG"
# Claude Code Configuration (generated by update.sh)
export ANTHROPIC_BASE_URL="$CLAUDE_URL"
export ANTHROPIC_API_KEY="$CLAUDE_KEY"
export ANTHROPIC_AUTH_TOKEN="$CLAUDE_KEY"
export ANTHROPIC_MODEL="$CLAUDE_MODEL"
export ANTHROPIC_SMALL_FAST_MODEL="$CLAUDE_SMALL_MODEL"
EOF
    chmod 600 "$CLAUDE_GLOBAL_CONFIG"
    echo -e "${GREEN}   ✅ Updated: $CLAUDE_GLOBAL_CONFIG${NC}"
else
    echo -e "🔧 Claude: ${YELLOW}disabled${NC}"
fi

# ==========================================
# [Phase 3] Update Gemini Config
# ==========================================
if [ "$GEMINI_MODE" = "isolated" ]; then
    echo -e "🔧 Gemini: ${GREEN}isolated${NC} mode"
    GEMINI_DIR="$CONFIG_CONTAINER_DIR/.gemini"
    mkdir -p "$GEMINI_DIR"
    echo '{"ide":{"enabled":true},"security":{"auth":{"selectedType":"gemini-api-key"}}}' > "$GEMINI_DIR/settings.json"

    GEMINI_SECRETS="$CONFIG_CONTAINER_DIR/.private_config/gemini.env"
    cat << EOF > "$GEMINI_SECRETS"
export GOOGLE_GEMINI_BASE_URL="$GEMINI_URL"
export GEMINI_API_KEY="$GEMINI_KEY"
export GOOGLE_API_KEY="$GEMINI_KEY"
export GEMINI_MODEL="$GEMINI_MODEL"
EOF
    chmod 600 "$GEMINI_SECRETS"
    echo -e "${GREEN}   ✅ Updated: $GEMINI_SECRETS${NC}"

elif [ "$GEMINI_MODE" = "global" ]; then
    echo -e "🔧 Gemini: ${GREEN}global${NC} mode"
    GEMINI_GLOBAL_DIR="$HOME/.gemini"
    mkdir -p "$GEMINI_GLOBAL_DIR"
    echo '{"ide":{"enabled":true},"security":{"auth":{"selectedType":"gemini-api-key"}}}' > "$GEMINI_GLOBAL_DIR/settings.json"

    GEMINI_GLOBAL_CONFIG="$HOME/.gemini_env"
    cat << EOF > "$GEMINI_GLOBAL_CONFIG"
# Gemini CLI Configuration (generated by update.sh)
export GOOGLE_GEMINI_BASE_URL="$GEMINI_URL"
export GEMINI_API_KEY="$GEMINI_KEY"
export GOOGLE_API_KEY="$GEMINI_KEY"
export GEMINI_MODEL="$GEMINI_MODEL"
EOF
    chmod 600 "$GEMINI_GLOBAL_CONFIG"
    echo -e "${GREEN}   ✅ Updated: $GEMINI_GLOBAL_CONFIG${NC}"
else
    echo -e "🔧 Gemini: ${YELLOW}disabled${NC}"
fi

# ==========================================
# [Phase 4] Update Codex Config
# ==========================================
if [ "$CODEX_MODE" = "global" ]; then
    echo -e "🔧 Codex: ${GREEN}global${NC} mode"
    CODEX_HOME_DIR="$HOME/.codex"
    mkdir -p "$CODEX_HOME_DIR"

    cat << EOF > "$CODEX_HOME_DIR/config.toml"
model_provider = "openai"
model = "$CODEX_MODEL"
model_reasoning_effort = "$CODEX_REASONING_EFFORT"
network_access = "$CODEX_NETWORK_ACCESS"
disable_response_storage = $CODEX_DISABLE_RESPONSE_STORAGE

[model_providers.openai]
name = "openai"
base_url = "$CODEX_URL"
wire_api = "$CODEX_WIRE_API"
requires_openai_auth = true
EOF
    echo -e "${GREEN}   ✅ Updated: $CODEX_HOME_DIR/config.toml${NC}"

    cat << EOF > "$CODEX_HOME_DIR/auth.json"
{
  "OPENAI_API_KEY": "$CODEX_KEY"
}
EOF
    chmod 600 "$CODEX_HOME_DIR/auth.json"
    echo -e "${GREEN}   ✅ Updated: $CODEX_HOME_DIR/auth.json${NC}"

    CODEX_GLOBAL_CONFIG="$HOME/.codex_env"
    cat << EOF > "$CODEX_GLOBAL_CONFIG"
# Codex CLI Configuration (generated by update.sh)
export OPENAI_API_KEY="$CODEX_KEY"
export OPENAI_BASE_URL="$CODEX_URL"
EOF
    chmod 600 "$CODEX_GLOBAL_CONFIG"
    echo -e "${GREEN}   ✅ Updated: $CODEX_GLOBAL_CONFIG${NC}"
else
    echo -e "🔧 Codex: ${YELLOW}disabled${NC}"
fi

# ==========================================
# [Phase 5] Update Conda Hooks (if isolated mode used)
# ==========================================
NEED_CONDA=false
if [ "$CLAUDE_MODE" = "isolated" ] || [ "$GEMINI_MODE" = "isolated" ]; then
    NEED_CONDA=true
fi

if [ "$NEED_CONDA" = true ]; then
    echo -e "\n${BLUE}>>> Updating Conda Hooks...${NC}"

    # Check if conda env exists
    if command -v conda &> /dev/null; then
        source "$(conda info --base)/etc/profile.d/conda.sh"

        CONDA_DIR="$(conda info --base)/envs/$CONDA_ENV_NAME"
        if [ -d "$CONDA_DIR" ]; then
            mkdir -p "$CONDA_DIR/etc/conda/activate.d"
            mkdir -p "$CONDA_DIR/etc/conda/deactivate.d"

            # Build activate script
            ACTIVATE_SCRIPT="$CONDA_DIR/etc/conda/activate.d/env_hook_isolation.sh"
            cat << 'HEADER' > "$ACTIVATE_SCRIPT"
#!/bin/bash
HEADER

            echo "export AI_CONFIG_ROOT=\"$CONFIG_CONTAINER_DIR\"" >> "$ACTIVATE_SCRIPT"

            if [ -n "$PROXY_URL" ]; then
                echo "export HTTP_PROXY=\"$PROXY_URL\" HTTPS_PROXY=\"$PROXY_URL\" ALL_PROXY=\"$PROXY_URL\"" >> "$ACTIVATE_SCRIPT"
            fi

            if [ "$CLAUDE_MODE" = "isolated" ]; then
                echo "source \"$CONFIG_CONTAINER_DIR/.private_config/claude.env\"" >> "$ACTIVATE_SCRIPT"
                echo "export XDG_CONFIG_HOME=\"$CONFIG_CONTAINER_DIR/.private_storage/config\"" >> "$ACTIVATE_SCRIPT"
                echo "export XDG_DATA_HOME=\"$CONFIG_CONTAINER_DIR/.private_storage/data\"" >> "$ACTIVATE_SCRIPT"
                echo "export XDG_STATE_HOME=\"$CONFIG_CONTAINER_DIR/.private_storage/state\"" >> "$ACTIVATE_SCRIPT"
                echo "export XDG_CACHE_HOME=\"$CONFIG_CONTAINER_DIR/.private_storage/cache\"" >> "$ACTIVATE_SCRIPT"
                echo "export NPM_CONFIG_USERCONFIG=\"$CONFIG_CONTAINER_DIR/.private_config/npmrc\"" >> "$ACTIVATE_SCRIPT"
            fi

            if [ "$GEMINI_MODE" = "isolated" ]; then
                echo "source \"$CONFIG_CONTAINER_DIR/.private_config/gemini.env\"" >> "$ACTIVATE_SCRIPT"
                echo "export GEMINI_HOME=\"$CONFIG_CONTAINER_DIR/.gemini\"" >> "$ACTIVATE_SCRIPT"
            fi

            if [ "$CODEX_MODE" = "global" ]; then
                echo "export OPENAI_API_KEY=\"$CODEX_KEY\"" >> "$ACTIVATE_SCRIPT"
                echo "export OPENAI_BASE_URL=\"$CODEX_URL\"" >> "$ACTIVATE_SCRIPT"
            fi

            echo 'echo "🤖 AI CLI environment activated"' >> "$ACTIVATE_SCRIPT"
            echo -e "${GREEN}   ✅ Updated: $ACTIVATE_SCRIPT${NC}"

            # Build deactivate script
            DEACTIVATE_SCRIPT="$CONDA_DIR/etc/conda/deactivate.d/env_hook_isolation.sh"
            cat << 'EOF' > "$DEACTIVATE_SCRIPT"
#!/bin/bash
unset ANTHROPIC_BASE_URL ANTHROPIC_API_KEY ANTHROPIC_AUTH_TOKEN ANTHROPIC_MODEL ANTHROPIC_SMALL_FAST_MODEL
unset GOOGLE_GEMINI_BASE_URL GEMINI_API_KEY GOOGLE_API_KEY GEMINI_MODEL GEMINI_HOME
unset OPENAI_API_KEY OPENAI_BASE_URL CODEX_HOME
unset AI_CONFIG_ROOT NPM_CONFIG_USERCONFIG
unset XDG_CONFIG_HOME XDG_DATA_HOME XDG_STATE_HOME XDG_CACHE_HOME
unset HTTP_PROXY HTTPS_PROXY ALL_PROXY
echo "🔌 AI CLI environment deactivated"
EOF
            echo -e "${GREEN}   ✅ Updated: $DEACTIVATE_SCRIPT${NC}"
        else
            echo -e "${YELLOW}   ⚠️  Conda env '$CONDA_ENV_NAME' not found, skipping hook update${NC}"
        fi
    else
        echo -e "${YELLOW}   ⚠️  Conda not found, skipping hook update${NC}"
    fi
fi

# ==========================================
# [Phase 6] Generate unified shell entry point
# ==========================================
echo -e "\n${BLUE}>>> Updating shell entry point...${NC}"
AI_CLI_ENV="$HOME/.ai_cli_env"
cat << 'HEADER' > "$AI_CLI_ENV"
# AI CLI Configuration (auto-generated by update.sh)
# DO NOT edit manually - run update.sh to regenerate
HEADER

[ "$CLAUDE_MODE" = "global" ] && echo '[ -f "$HOME/.claude_env" ] && source "$HOME/.claude_env"' >> "$AI_CLI_ENV"
[ "$GEMINI_MODE" = "global" ] && echo '[ -f "$HOME/.gemini_env" ] && source "$HOME/.gemini_env"' >> "$AI_CLI_ENV"
[ "$CODEX_MODE" = "global" ] && echo '[ -f "$HOME/.codex_env" ] && source "$HOME/.codex_env"' >> "$AI_CLI_ENV"

chmod 600 "$AI_CLI_ENV"
echo -e "${GREEN}   ✅ Updated: $AI_CLI_ENV${NC}"

# Check if shell profile has the entry
SHELL_PROFILE="$HOME/.bashrc"
[ -n "$ZSH_VERSION" ] || [ "$SHELL" = "/bin/zsh" ] || [ "$SHELL" = "/usr/bin/zsh" ] && SHELL_PROFILE="$HOME/.zshrc"

if [ -f "$SHELL_PROFILE" ] && ! grep -qF ".ai_cli_env" "$SHELL_PROFILE"; then
    echo -e "${YELLOW}   ⚠️  ~/.ai_cli_env not found in $SHELL_PROFILE${NC}"
    echo -e "${YELLOW}      Run setup.sh or manually add: [ -f \"\$HOME/.ai_cli_env\" ] && source \"\$HOME/.ai_cli_env\"${NC}"
fi

# ==========================================
# [Phase 7] Summary
# ==========================================
echo -e "\n${GREEN}✅ Configuration Updated!${NC}"
echo "----------------------------------------------------------------"

echo -e "\n📝 To apply changes:"
if [ "$NEED_CONDA" = true ]; then
    echo -e "   ${YELLOW}conda deactivate && conda activate $CONDA_ENV_NAME${NC}"
fi
echo -e "   ${YELLOW}source ~/.bashrc${NC}  (for global mode)"

# Warn about missing CLI tools
MISSING_TOOLS=""
if [ "$CLAUDE_MODE" != "disabled" ] && [ "$CLAUDE_INSTALLED" = false ]; then
    MISSING_TOOLS="$MISSING_TOOLS claude"
fi
if [ "$GEMINI_MODE" != "disabled" ] && [ "$GEMINI_INSTALLED" = false ]; then
    MISSING_TOOLS="$MISSING_TOOLS gemini"
fi
if [ "$CODEX_MODE" != "disabled" ] && [ "$CODEX_INSTALLED" = false ]; then
    MISSING_TOOLS="$MISSING_TOOLS codex"
fi

if [ -n "$MISSING_TOOLS" ]; then
    echo -e "\n${YELLOW}⚠️  The following CLI tools are configured but not installed:${NC}"
    echo -e "  $MISSING_TOOLS"
    echo -e "${YELLOW}   Run ${GREEN}./setup.sh${YELLOW} to install them, or install manually:${NC}"
    [[ "$MISSING_TOOLS" == *"claude"* ]] && echo -e "   npm install -g @anthropic-ai/claude-code"
    [[ "$MISSING_TOOLS" == *"gemini"* ]] && echo -e "   npm install -g @google/gemini-cli"
    [[ "$MISSING_TOOLS" == *"codex"* ]] && echo -e "   npm install -g @openai/codex"
fi
